#!/usr/bin/env python3
"""
Compile a single, deduplicated dependency list from every manifest copied
into ort-review/manifests/ (Python, JS/npm, Go, Docker).

Snapshot date: 2026-08-26

Usage:
    python compile_dependencies.py
    -> writes combined-dependencies.txt next to this script
"""
import json
import re
from pathlib import Path

MANIFESTS_DIR = Path(__file__).parent / "manifests"
OUTPUT_FILE = Path(__file__).parent / "combined-dependencies.txt"


def parse_pip_requirements(path: Path):
    deps = set()
    project = path.stem.replace(".requirements", "")
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        match = re.match(r"^([A-Za-z0-9_.\-]+)(?:\[[^\]]+\])?\s*(==|>=|<=|~=|!=|>|<)?\s*([A-Za-z0-9_.\-]*)", line)
        if match:
            name, _, version = match.groups()
            deps.add(("pip", name, version or "", project, "direct"))
    return deps


def parse_setup_py(path: Path):
    deps = set()
    project = path.stem.replace(".setup", "")
    text = path.read_text(encoding="utf-8")
    match = re.search(r"install_requires\s*=\s*\[(.*?)\]", text, re.S)
    if not match:
        return deps
    for item in re.findall(r"['\"]([^'\"]+)['\"]", match.group(1)):
        item = item.strip()
        if not item or item.startswith("#"):
            continue
        spec = re.match(r"^([A-Za-z0-9_.\-]+)\s*(==|>=|<=|~=|!=|>|<)?\s*([A-Za-z0-9_.\-]*)", item)
        if spec:
            name, _, version = spec.groups()
            deps.add(("pip", name, version or "", project, "direct"))
    return deps


def parse_package_json(path: Path):
    deps = set()
    project = path.stem.replace(".package", "")
    data = json.loads(path.read_text(encoding="utf-8"))
    for key in ("dependencies", "devDependencies"):
        for name, version in data.get(key, {}).items():
            deps.add(("npm", name, version.lstrip("^~>=< "), project, key))
    return deps


def parse_go_mod(path: Path):
    deps = set()
    text = path.read_text(encoding="utf-8")
    for match in re.finditer(r"^\s*([^\s]+)\s+(v[0-9][^\s]*)(\s*//\s*indirect)?", text, re.M):
        module, version, indirect = match.groups()
        if module in ("go", "toolchain", "module", "require", "(", ")"):
            continue
        scope = "indirect" if indirect else "direct"
        deps.add(("go", module, version, "go", scope))
    return deps


def parse_dockerfile(path: Path):
    deps = set()
    raw_text = path.read_text(encoding="utf-8")
    project = path.stem.replace(".Dockerfile", "") + ".Dockerfile"
    # Join backslash line-continuations so multi-line RUN commands become one line.
    text = re.sub(r"\\\r?\n", " ", raw_text)

    for match in re.finditer(r"^\s*FROM\s+([^\s]+)(?:\s+AS\s+\S+)?", raw_text, re.M | re.I):
        image = match.group(1)
        if ":" in image:
            name, version = image.split(":", 1)
        else:
            name, version = image, "latest"
        deps.add(("docker-image", name, version, project, "base-image"))

    for match in re.finditer(r"(?:apt-get install|apk add)([^\n&|]*)", text, re.I):
        line = match.group(1)
        for token in line.split():
            if token.startswith("-") or token in ("update", "&&", "install"):
                continue
            deps.add(("os-package", token, "", project, "os-package"))
    return deps


PARSERS = {
    "requirements.txt": parse_pip_requirements,
    "setup.py": parse_setup_py,
    "package.json": parse_package_json,
    "go.mod": parse_go_mod,
    "Dockerfile": parse_dockerfile,
}


def resolve_parser(file_path: Path):
    name = file_path.name
    for suffix, parser in PARSERS.items():
        if name == suffix or name.endswith("." + suffix):
            return parser
    return None


def main():
    all_deps = set()
    for file_path in sorted(MANIFESTS_DIR.rglob("*")):
        if not file_path.is_file() or file_path.name == "package-lock.json" or file_path.name == "go.sum":
            continue
        parser = resolve_parser(file_path)
        if not parser:
            continue
        found = parser(file_path)
        print(f"{file_path.relative_to(MANIFESTS_DIR)}: {len(found)} dependencies")
        all_deps.update(found)

    lines = [
        f"{ecosystem}\t{name}\t{version}\t{project}\t{scope}"
        for ecosystem, name, version, project, scope in sorted(all_deps)
    ]
    OUTPUT_FILE.write_text(
        "# Combined, deduplicated dependency list — generated by compile_dependencies.py\n"
        "# Snapshot date: 2026-08-26\n"
        "# Columns: ecosystem\tname\tversion\tproject\tscope\n" + "\n".join(lines) + "\n",
        encoding="utf-8",
    )
    print(f"\nWrote {len(lines)} unique dependencies to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
